---
- hosts: eoi-server2
  vars_files:
    - vars.yml
  gather_facts: false

  tasks:

    - name: Hacer un git clone del repositorio 
      git:
        repo: "{{ github_url }}"
        dest: "{{ project_path }}"
        force: true
      
    - name: Crear el entorno virtual e instalar las dependencias 
      ansible.builtin.pip:
        requirements: "{{ project_path }}/requirements.txt"
        virtualenv: "{{ project_path }}/.venv"

    - name: Dar permisios de ejecución al fichero manage.py para poder hacer acciones
      file:
        path: "{{ project_path }}/manage.py"
        mode: "0777"

    - name: Ejecutar las migraciones
      community.general.django_manage:
        command: migrate
        project_path: "{{ project_path }}"
        virtualenv: "{{ project_path }}/.venv"
      
    - name: Cargar los datos iniciales en la base de datos
      django_manage:
        command: loaddata
        project_path: "{{ project_path }}"
        virtualenv: "{{ project_path }}/.venv"
        fixtures: "{{ project_path }}/db.json"
